apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mq4h1m01x-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mq4h1m01x-go 
  name: mq4h1m01x-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mq4h1m01x-go 
