apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: mq4h1m01x-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:f5bce4bb9ed509b56dafd7b2970b728d26233c6a@sha256:588bd3ebcef8ba9613c2065231a65203274cba0d93645ab5df412cda9b6f69f7
          name: container-image
